export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING = 'SET_PLAYING'

export const SET_FULL_SCREEN = 'SET_FULLSCREEN'

export const SET_PLAY_LIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCELIST'

export const SET_MODE = 'SET_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENTINDEX'
